/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import domen.Program;
import domen.VirtuelnaMasina;
import gui.table_model.IzaberiVMTableModel;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import kontroler.Kontroler;

/**
 *
 * @author vagrant
 */
public class GlavnaForma extends javax.swing.JFrame {

    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma() {
        initComponents();

        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                Kontroler.zatvoriAplikaciju();
            }

        });

        prikaziAdministraciju(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jScrollPane3 = new javax.swing.JScrollPane();
        jpnlCheckBoksevi = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jbtnCard1PokreniVM = new javax.swing.JButton();
        jbtnCard1nazad = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtxtPronadji = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblIzaberiVM = new javax.swing.JTable();
        jbtnCard0Dalje = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jtxtImeIzabraneVM = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxtPutanjaDoFoldera = new javax.swing.JTextField();
        jbtnBrowse = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxtAreaOpisVM = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jpnlIzbor = new javax.swing.JPanel();
        jlblIzbor = new javax.swing.JLabel();
        jtxtPutanja = new javax.swing.JTextField();
        jbtnIzbor = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jpnlVM = new javax.swing.JPanel();
        jlblVM = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jlistVM = new javax.swing.JList<>();
        jlblOpisVM = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtxtAreaOpis = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jpnlProgram = new javax.swing.JPanel();
        jlblProgram = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        jMenu3.setText("jMenu3");

        jpnlCheckBoksevi.setLayout(new javax.swing.BoxLayout(jpnlCheckBoksevi, javax.swing.BoxLayout.Y_AXIS));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Izaberite programe");
        jpnlCheckBoksevi.add(jLabel5);

        jScrollPane3.setViewportView(jpnlCheckBoksevi);

        jbtnCard1PokreniVM.setText("Pokreni VM");
        jbtnCard1PokreniVM.setMaximumSize(new java.awt.Dimension(120, 25));
        jbtnCard1PokreniVM.setMinimumSize(new java.awt.Dimension(120, 25));
        jbtnCard1PokreniVM.setPreferredSize(new java.awt.Dimension(120, 25));
        jbtnCard1PokreniVM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCard1PokreniVMActionPerformed(evt);
            }
        });

        jbtnCard1nazad.setText("Nazad");
        jbtnCard1nazad.setMaximumSize(new java.awt.Dimension(120, 25));
        jbtnCard1nazad.setMinimumSize(new java.awt.Dimension(120, 25));
        jbtnCard1nazad.setPreferredSize(new java.awt.Dimension(120, 25));
        jbtnCard1nazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCard1nazadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnCard1nazad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnCard1PokreniVM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnCard1PokreniVM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnCard1nazad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Izaberite virtuelnu masinu");

        jtxtPronadji.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtPronadjiKeyReleased(evt);
            }
        });

        jLabel6.setText("Pronadji VM");

        jtblIzaberiVM.setModel(new IzaberiVMTableModel());
        jScrollPane1.setViewportView(jtblIzaberiVM);

        jbtnCard0Dalje.setText("Dalje...");
        jbtnCard0Dalje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCard0DaljeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 974, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jtxtImeIzabraneVM.setEditable(false);

        jLabel4.setText("Opis VM:");

        jLabel7.setText("Odaberite putanju:");

        jtxtPutanjaDoFoldera.setEditable(false);

        jbtnBrowse.setText("Browse...");
        jbtnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseActionPerformed(evt);
            }
        });

        jScrollPane2.setEnabled(false);

        jtxtAreaOpisVM.setEditable(false);
        jtxtAreaOpisVM.setColumns(20);
        jtxtAreaOpisVM.setLineWrap(true);
        jtxtAreaOpisVM.setRows(5);
        jScrollPane2.setViewportView(jtxtAreaOpisVM);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 974, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 583, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("VirtualIrc");

        jlblIzbor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblIzbor.setText("Izaberi putanju:");

        jtxtPutanja.setEditable(false);
        jtxtPutanja.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxtPutanja.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jbtnIzbor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtnIzbor.setText("Izbor");
        jbtnIzbor.setPreferredSize(new java.awt.Dimension(91, 29));

        javax.swing.GroupLayout jpnlIzborLayout = new javax.swing.GroupLayout(jpnlIzbor);
        jpnlIzbor.setLayout(jpnlIzborLayout);
        jpnlIzborLayout.setHorizontalGroup(
            jpnlIzborLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlIzborLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblIzbor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtPutanja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnIzbor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpnlIzborLayout.setVerticalGroup(
            jpnlIzborLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlIzborLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jpnlIzborLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblIzbor)
                    .addComponent(jtxtPutanja, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnIzbor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Instalacija");

        jlblVM.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblVM.setText("Izaberi virtuelnu mašinu:");

        jlistVM.setBackground(new java.awt.Color(240, 240, 240));
        jlistVM.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlistVM.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jlistVM);

        jlblOpisVM.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblOpisVM.setText("Opis virtuelne mašine:");

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setMaximumSize(new java.awt.Dimension(246, 32767));

        jtxtAreaOpis.setBackground(new java.awt.Color(240, 240, 240));
        jtxtAreaOpis.setColumns(20);
        jtxtAreaOpis.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxtAreaOpis.setRows(5);
        jtxtAreaOpis.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtxtAreaOpis.setMaximumSize(new java.awt.Dimension(244, 2147483647));
        jScrollPane5.setViewportView(jtxtAreaOpis);

        javax.swing.GroupLayout jpnlProgramLayout = new javax.swing.GroupLayout(jpnlProgram);
        jpnlProgram.setLayout(jpnlProgramLayout);
        jpnlProgramLayout.setHorizontalGroup(
            jpnlProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
        );
        jpnlProgramLayout.setVerticalGroup(
            jpnlProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 225, Short.MAX_VALUE)
        );

        jScrollPane6.setViewportView(jpnlProgram);

        jlblProgram.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblProgram.setText("Izaberi programe:");

        javax.swing.GroupLayout jpnlVMLayout = new javax.swing.GroupLayout(jpnlVM);
        jpnlVM.setLayout(jpnlVMLayout);
        jpnlVMLayout.setHorizontalGroup(
            jpnlVMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlVMLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlVMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpnlVMLayout.createSequentialGroup()
                        .addComponent(jlblOpisVM)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpnlVMLayout.createSequentialGroup()
                        .addGroup(jpnlVMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblVM)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jpnlVMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblProgram)
                            .addComponent(jScrollPane6))))
                .addContainerGap())
        );
        jpnlVMLayout.setVerticalGroup(
            jpnlVMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlVMLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlVMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblVM)
                    .addComponent(jlblProgram))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnlVMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6)
                    .addComponent(jScrollPane4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlblOpisVM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );

        jMenu1.setText("Administrator");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("O aplikaciji");
        jMenuBar1.add(jMenu2);

        jMenu4.setText("O nama");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlIzbor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnlVM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(202, 202, 202))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnlIzbor, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnlVM, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(592, 652));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCard1PokreniVMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCard1PokreniVMActionPerformed
        Kontroler.pokreniVM();
    }//GEN-LAST:event_jbtnCard1PokreniVMActionPerformed

    private void jbtnCard1nazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCard1nazadActionPerformed
        prikaziCard0();
    }//GEN-LAST:event_jbtnCard1nazadActionPerformed

    private void jbtnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowseActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int opcija = fc.showOpenDialog(this);
        String putanja;
        if (opcija == JFileChooser.APPROVE_OPTION) {
            putanja = fc.getSelectedFile().getAbsolutePath();
            getPutanjaDoFoldera().setText(putanja);
        } else {
            putanja = "";
        }
        Kontroler.NamestiPutanjuDoFoldera(putanja);

    }//GEN-LAST:event_jbtnBrowseActionPerformed

    private void jbtnCard0DaljeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCard0DaljeActionPerformed
        int selektovaniRed = jtblIzaberiVM.getSelectedRow();

        IzaberiVMTableModel iVM = (IzaberiVMTableModel) jtblIzaberiVM.getModel();

        if (selektovaniRed == -1) {
            JOptionPane.showMessageDialog(this, "Izaberite VM", "Greska", JOptionPane.ERROR_MESSAGE);
        } else {
            VirtuelnaMasina vm = iVM.vratiVM(selektovaniRed);

            if (vm != null) {
                Kontroler.card0Dalje(vm);
            }
            //            JOptionPane.showMessageDialog(this, vm);
        }
    }//GEN-LAST:event_jbtnCard0DaljeActionPerformed

    private void jtxtPronadjiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPronadjiKeyReleased
        Kontroler.search(jtxtPronadji.getText());
    }//GEN-LAST:event_jtxtPronadjiKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JButton jbtnBrowse;
    private javax.swing.JButton jbtnCard0Dalje;
    private javax.swing.JButton jbtnCard1PokreniVM;
    private javax.swing.JButton jbtnCard1nazad;
    private javax.swing.JButton jbtnIzbor;
    private javax.swing.JLabel jlblIzbor;
    private javax.swing.JLabel jlblOpisVM;
    private javax.swing.JLabel jlblProgram;
    private javax.swing.JLabel jlblVM;
    private javax.swing.JList<String> jlistVM;
    private javax.swing.JPanel jpnlCheckBoksevi;
    private javax.swing.JPanel jpnlIzbor;
    private javax.swing.JPanel jpnlProgram;
    private javax.swing.JPanel jpnlVM;
    private javax.swing.JTable jtblIzaberiVM;
    private javax.swing.JTextArea jtxtAreaOpis;
    private javax.swing.JTextArea jtxtAreaOpisVM;
    private javax.swing.JTextField jtxtImeIzabraneVM;
    private javax.swing.JTextField jtxtPronadji;
    private javax.swing.JTextField jtxtPutanja;
    private javax.swing.JTextField jtxtPutanjaDoFoldera;
    // End of variables declaration//GEN-END:variables

    public void prikaziAdministraciju(boolean b) {
//        jpnlAdministracija.setVisible(b);
    }

    public javax.swing.JTextField getTxtPronadji() {
        return jtxtPronadji;
    }

    public IzaberiVMTableModel getIzaberiVMTableModel() {
        return (IzaberiVMTableModel) jtblIzaberiVM.getModel();
    }

    public JTextField getJtxtImeIzabraneVirtuelneMasine() {
        return jtxtImeIzabraneVM;
    }

    public void prikaziCard1() {
        sakrijSvePanele();
//        card1.setVisible(true);
    }

    public void sakrijSvePanele() {
//        card0.setVisible(false);
//        card1.setVisible(false);
    }

    public JTextArea getJTxtOpisVM() {
        return jtxtAreaOpisVM;
    }

    public JPanel getJPanelCheckBoksevi() {
        return jpnlCheckBoksevi;
    }

    private void prikaziCard0() {
        sakrijSvePanele();
//        card0.setVisible(true);
    }

    public JTextField getPutanjaDoFoldera() {
        return jtxtPutanjaDoFoldera;
    }

    public void generisiCheckBokseve(List<Program> listaPrograma) {
        for (Program p : listaPrograma) {
            JCheckBox jcb = new JCheckBox(p.getIme());
            jpnlCheckBoksevi.add(jcb);
            Kontroler.dodajCheckBoksUListu(jcb);
        }
    }

    public JPanel getJpnlCheckBoksevi() {
        return jpnlCheckBoksevi;
    }

    public void setJpnlCheckBoksevi(JPanel jpnlCheckBoksevi) {
        this.jpnlCheckBoksevi = jpnlCheckBoksevi;
    }
    
}
