/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import javax.swing.JDialog;

/**
 *
 * @author stanimirovic.marko
 */
public class ProgresInstalacije extends javax.swing.JFrame {

    /**
     * Creates new form ProgresInstalacije
     */
    public ProgresInstalacije() {
        initComponents();
        jtxtAreaKonzola.setText("");
        jbtnPrekini.setContentAreaFilled(true);
        jbtnRDP.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtAreaKonzola = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jbtnPrekini = new javax.swing.JButton();
        jbtnRDP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Instalacija");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jtxtAreaKonzola.setEditable(false);
        jtxtAreaKonzola.setBackground(new java.awt.Color(51, 51, 51));
        jtxtAreaKonzola.setColumns(20);
        jtxtAreaKonzola.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxtAreaKonzola.setForeground(new java.awt.Color(153, 255, 153));
        jtxtAreaKonzola.setLineWrap(true);
        jtxtAreaKonzola.setRows(5);
        jtxtAreaKonzola.setBorder(null);
        jScrollPane1.setViewportView(jtxtAreaKonzola);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Instalacija je u toku.");

        jbtnPrekini.setBackground(java.awt.Color.red);
        jbtnPrekini.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnPrekini.setText("Prekini");
        jbtnPrekini.setBorder(null);
        jbtnPrekini.setBorderPainted(false);
        jbtnPrekini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrekiniActionPerformed(evt);
            }
        });

        jbtnRDP.setText("RDP");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(jbtnPrekini, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnRDP)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnRDP, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jbtnPrekini, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnPrekiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrekiniActionPerformed
        if (jbtnPrekini.getText().equalsIgnoreCase("Prekini")) {
            // PREKINI INSTALACIJU
            // IZBRISI SVE IZ FOLDERA
            this.dispose();
        } else if (jbtnPrekini.getText().equalsIgnoreCase("Ok")) {
            // UGASI DIJALOG
            this.dispose();
        }
    }//GEN-LAST:event_jbtnPrekiniActionPerformed

    /**
     * @param args the command line arguments
     */
    public void setTextJTxtAreaKonzola(String tekst) {
        jtxtAreaKonzola.append(tekst);
        jtxtAreaKonzola.setCaretPosition(jtxtAreaKonzola.getText().length());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnPrekini;
    private javax.swing.JButton jbtnRDP;
    private javax.swing.JTextArea jtxtAreaKonzola;
    // End of variables declaration//GEN-END:variables

    public void setNewNameForJbtnKonzola(String naziv) {
        if (naziv.equalsIgnoreCase("ok")) {
            jbtnPrekini.setText(naziv);
            jbtnPrekini.setBackground(Color.GREEN);
            jbtnPrekini.setBorder(null);
            jbtnRDP.setVisible(true);
        }
    }
}
