/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JDialog;

/**
 *
 * @author stanimirovic.marko
 */
public class ProgresInstalacije extends javax.swing.JDialog {

    /**
     * Creates new form ProgresInstalacije
     */
    public ProgresInstalacije(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jtxtAreaKonzola.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtAreaKonzola = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Instalacija");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jtxtAreaKonzola.setEditable(false);
        jtxtAreaKonzola.setBackground(new java.awt.Color(240, 240, 240));
        jtxtAreaKonzola.setColumns(20);
        jtxtAreaKonzola.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxtAreaKonzola.setLineWrap(true);
        jtxtAreaKonzola.setRows(5);
        jtxtAreaKonzola.setBorder(null);
        jScrollPane1.setViewportView(jtxtAreaKonzola);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Instalacija je u toku.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 386, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public void setTextJTxtAreaKonzola(String tekst) {
        jtxtAreaKonzola.setText(jtxtAreaKonzola.getText() + tekst);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jtxtAreaKonzola;
    // End of variables declaration//GEN-END:variables
}
